alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: poketrivia-server.prathamjaiswal.com
  type: PRIMARY
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: poketrivia-server
    cors:
      allow_origins:
      - exact: https://poketrivia.prathamjaiswal.com
      allow_headers:
      - Content-Type
      - Authorization
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: backend-poketrivia
region: blr
services:
- environment_slug: node-js
  envs:
  - key: AUTH0_AUDIENCE
    scope: RUN_AND_BUILD_TIME
    value: ${AUTH0_AUDIENCE}
  - key: AUTH0_DOMAIN
    scope: RUN_AND_BUILD_TIME
    value: ${AUTH0_DOMAIN}
  - key: AUTH0_TOKEN_SIGN_ALGO
    scope: RUN_AND_BUILD_TIME
    value: ${AUTH0_TOKEN_SIGN_ALGO}
  - key: MONGODB_URI
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: ${MONGODB_URI}
  - key: ALLOWED_URI
    scope: RUN_AND_BUILD_TIME
    value: https://poketrivia.prathamjaiswal.com
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: 24.14.0
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "8081"
  github:
    branch: main
    deploy_on_push: false
    repo: pratham-jaiswal/poketrivia
  http_port: 8081
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: poketrivia-server
  run_command: npm start
  source_dir: server
